require("mini.bufremove").setup()
require("mini.comment").setup()
require("mini.cursorword").setup()
require("mini.surround").setup()
require("mini.trailspace").setup()
require("mini.tabline").setup()
