[settings]
lockfile = true

[tools]
chezmoi = "latest"
go = "latest"
golangci-lint = "latest"
jq = "latest"
node = "lts"
opentofu = "latest"
pnpm = "latest"
python = "latest"
usage = "latest"
uv = "latest"
yq = "latest"
